services:
  web:
    build: .
    ports:
      - "${PORT:-8000}:80"
    volumes:
      - ${PATH_DATABASE:-./docker_data/db/}:/app/db/
      - ${PATH_MEDIA:-./docker_data/media/}:/app/data/media/
    env_file:
      - .env
